package org.lightadmin.demo.model;
// Generated Nov 1, 2015 1:04:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QaData generated by hbm2java
 */
@Entity
@Table(name = "qa_data")
public class QaData implements java.io.Serializable {

	private Long dataId;
	private String dataName;
	private String dataValue;
	private String dataDescription;
	/*private Set qaTestResults = new HashSet(0);
	private Set qaSteps = new HashSet(0);*/

	public QaData() {
	}

	public QaData(Long dataId) {
		this.dataId = dataId;
	}

	public QaData(Long dataId, String dataName, String dataValue, String dataDescription, Set qaTestResults,
			Set qaSteps) {
		this.dataId = dataId;
		this.dataName = dataName;
		this.dataValue = dataValue;
		this.dataDescription = dataDescription;
		/*this.qaTestResults = qaTestResults;
		this.qaSteps = qaSteps;*/
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "DATA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getDataId() {
		return this.dataId;
	}

	public void setDataId(Long dataId) {
		this.dataId = dataId;
	}

	@Column(name = "DATA_NAME", length = 30)
	public String getDataName() {
		return this.dataName;
	}

	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

	@Column(name = "DATA_VALUE", length = 100)
	public String getDataValue() {
		return this.dataValue;
	}

	public void setDataValue(String dataValue) {
		this.dataValue = dataValue;
	}

	@Column(name = "DATA_DESCRIPTION", length = 200)
	public String getDataDescription() {
		return this.dataDescription;
	}

	public void setDataDescription(String dataDescription) {
		this.dataDescription = dataDescription;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaData")
	public Set getQaTestResults() {
		return this.qaTestResults;
	}

	public void setQaTestResults(Set qaTestResults) {
		this.qaTestResults = qaTestResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaData")
	public Set getQaSteps() {
		return this.qaSteps;
	}

	public void setQaSteps(Set qaSteps) {
		this.qaSteps = qaSteps;
	}*/

}
