package org.lightadmin.demo.model;
// Generated Nov 1, 2015 1:04:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QaFlow generated by hbm2java
 */
@Entity
@Table(name = "qa_flow")
public class QaFlow implements java.io.Serializable {

	private Long flowId;
	private String flowDesc;
	/*private Set qaDepDatas = new HashSet(0);
	private Set qaResultTestCases = new HashSet(0);
	private Set qaFlowStepMapsForRefFlowId = new HashSet(0);
	private Set qaTestCaseFlowMaps = new HashSet(0);
	private Set qaFlowStepMapsForFlowId = new HashSet(0);
	private Set qaResults = new HashSet(0);
	private Set qaFlowTestMaps = new HashSet(0);*/

	public QaFlow() {
	}

	public QaFlow(Long flowId) {
		this.flowId = flowId;
	}

	public QaFlow(Long flowId, String flowDesc, Set qaDepDatas, Set qaResultTestCases, Set qaFlowStepMapsForRefFlowId,
			Set qaTestCaseFlowMaps, Set qaFlowStepMapsForFlowId, Set qaResults, Set qaFlowTestMaps) {
		this.flowId = flowId;
		this.flowDesc = flowDesc;
		/*this.qaDepDatas = qaDepDatas;
		this.qaResultTestCases = qaResultTestCases;
		this.qaFlowStepMapsForRefFlowId = qaFlowStepMapsForRefFlowId;
		this.qaTestCaseFlowMaps = qaTestCaseFlowMaps;
		this.qaFlowStepMapsForFlowId = qaFlowStepMapsForFlowId;
		this.qaResults = qaResults;
		this.qaFlowTestMaps = qaFlowTestMaps;*/
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "FLOW_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getFlowId() {
		return this.flowId;
	}

	public void setFlowId(Long flowId) {
		this.flowId = flowId;
	}

	@Column(name = "FLOW_DESC", length = 200)
	public String getFlowDesc() {
		return this.flowDesc;
	}

	public void setFlowDesc(String flowDesc) {
		this.flowDesc = flowDesc;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlow")
	public Set getQaDepDatas() {
		return this.qaDepDatas;
	}

	public void setQaDepDatas(Set qaDepDatas) {
		this.qaDepDatas = qaDepDatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlow")
	public Set getQaResultTestCases() {
		return this.qaResultTestCases;
	}

	public void setQaResultTestCases(Set qaResultTestCases) {
		this.qaResultTestCases = qaResultTestCases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlowByRefFlowId")
	public Set getQaFlowStepMapsForRefFlowId() {
		return this.qaFlowStepMapsForRefFlowId;
	}

	public void setQaFlowStepMapsForRefFlowId(Set qaFlowStepMapsForRefFlowId) {
		this.qaFlowStepMapsForRefFlowId = qaFlowStepMapsForRefFlowId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlow")
	public Set getQaTestCaseFlowMaps() {
		return this.qaTestCaseFlowMaps;
	}

	public void setQaTestCaseFlowMaps(Set qaTestCaseFlowMaps) {
		this.qaTestCaseFlowMaps = qaTestCaseFlowMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlowByFlowId")
	public Set getQaFlowStepMapsForFlowId() {
		return this.qaFlowStepMapsForFlowId;
	}

	public void setQaFlowStepMapsForFlowId(Set qaFlowStepMapsForFlowId) {
		this.qaFlowStepMapsForFlowId = qaFlowStepMapsForFlowId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlow")
	public Set getQaResults() {
		return this.qaResults;
	}

	public void setQaResults(Set qaResults) {
		this.qaResults = qaResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaFlow")
	public Set getQaFlowTestMaps() {
		return this.qaFlowTestMaps;
	}

	public void setQaFlowTestMaps(Set qaFlowTestMaps) {
		this.qaFlowTestMaps = qaFlowTestMaps;
	}*/

}
