package org.lightadmin.demo.model;
// Generated Nov 1, 2015 1:04:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QaFlowStepMapId generated by hbm2java
 */
@Embeddable
public class QaFlowStepMapId implements java.io.Serializable {

	private Long flowId;
	private Long stepId;

	public QaFlowStepMapId() {
	}

	public QaFlowStepMapId(Long flowId, Long stepId) {
		this.flowId = flowId;
		this.stepId = stepId;
	}

	@Column(name = "FLOW_ID", nullable = false, precision = 10, scale = 0)
	public Long getFlowId() {
		return this.flowId;
	}

	public void setFlowId(Long flowId) {
		this.flowId = flowId;
	}

	@Column(name = "STEP_ID", nullable = false, precision = 10, scale = 0)
	public Long getStepId() {
		return this.stepId;
	}

	public void setStepId(Long stepId) {
		this.stepId = stepId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QaFlowStepMapId))
			return false;
		QaFlowStepMapId castOther = (QaFlowStepMapId) other;

		return (this.getFlowId() == castOther.getFlowId()) && (this.getStepId() == castOther.getStepId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result +  this.getFlowId().intValue();
		result = 37 * result +  this.getStepId().intValue();
		return result;
	}

}
