package org.lightadmin.demo.model;
// Generated Nov 5, 2015 5:47:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QaResultTestCase generated by hbm2java
 */
@Entity
@Table(name = "qa_result_test_case")
public class QaResultTestCase implements java.io.Serializable {

	private Integer resultTestCaseId;
	private QaFlow qaFlow;
	private QaStep qaStep;
	private QaTestCase qaTestCase;
	private String threadId;
	private String status;

	public QaResultTestCase() {
	}

	public QaResultTestCase(QaFlow qaFlow, QaStep qaStep, QaTestCase qaTestCase, String threadId) {
		this.qaFlow = qaFlow;
		this.qaStep = qaStep;
		this.qaTestCase = qaTestCase;
		this.threadId = threadId;
	}

	public QaResultTestCase(QaFlow qaFlow, QaStep qaStep, QaTestCase qaTestCase, String threadId, String status) {
		this.qaFlow = qaFlow;
		this.qaStep = qaStep;
		this.qaTestCase = qaTestCase;
		this.threadId = threadId;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "RESULT_TEST_CASE_ID", unique = true, nullable = false)
	public Integer getResultTestCaseId() {
		return this.resultTestCaseId;
	}

	public void setResultTestCaseId(Integer resultTestCaseId) {
		this.resultTestCaseId = resultTestCaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLOW_ID", nullable = false)
	public QaFlow getQaFlow() {
		return this.qaFlow;
	}

	public void setQaFlow(QaFlow qaFlow) {
		this.qaFlow = qaFlow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STEP_ID", nullable = false)
	public QaStep getQaStep() {
		return this.qaStep;
	}

	public void setQaStep(QaStep qaStep) {
		this.qaStep = qaStep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_CASE_ID", nullable = false)
	public QaTestCase getQaTestCase() {
		return this.qaTestCase;
	}

	public void setQaTestCase(QaTestCase qaTestCase) {
		this.qaTestCase = qaTestCase;
	}

	@Column(name = "THREAD_ID", nullable = false, length = 20)
	public String getThreadId() {
		return this.threadId;
	}

	public void setThreadId(String threadId) {
		this.threadId = threadId;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
