package org.lightadmin.demo.model;
// Generated Nov 5, 2015 4:50:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QaTestSuite generated by hbm2java
 */
@Entity
@Table(name = "qa_test_suite")
public class QaTestSuite implements java.io.Serializable {

	private Long testSuiteId;
	private Application application;
	private String testSuiteName;
	private String newBrowser;

	public QaTestSuite() {
	}

	public QaTestSuite(Long testSuiteId) {
		this.testSuiteId = testSuiteId;
	}

	public QaTestSuite(Long testSuiteId, Application application, String testSuiteName, String newBrowser) {
		this.testSuiteId = testSuiteId;
		this.application = application;
		this.testSuiteName = testSuiteName;
		this.newBrowser = newBrowser;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "TEST_SUITE_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getTestSuiteId() {
		return this.testSuiteId;
	}

	public void setTestSuiteId(Long testSuiteId) {
		this.testSuiteId = testSuiteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLICATION_ID")
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@Column(name = "TEST_SUITE_NAME", length = 100)
	public String getTestSuiteName() {
		return this.testSuiteName;
	}

	public void setTestSuiteName(String testSuiteName) {
		this.testSuiteName = testSuiteName;
	}

	@Column(name = "NEW_BROWSER", length = 1)
	public String getNewBrowser() {
		return this.newBrowser;
	}

	public void setNewBrowser(String newBrowser) {
		this.newBrowser = newBrowser;
	}

}


