package org.lightadmin.demo.model;
// Generated Nov 1, 2015 1:04:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QaDepData generated by hbm2java
 */
@Entity
@Table(name = "qa_dep_data")
public class QaDepData implements java.io.Serializable {

	private QaDepDataId id;
	private QaFlow qaFlow;
	private QaStep qaStep;
	private String dataKey;
	private String dataValue;
	private Date createdDt;

	public QaDepData() {
	}

	public QaDepData(QaDepDataId id, QaFlow qaFlow, QaStep qaStep) {
		this.id = id;
		this.qaFlow = qaFlow;
		this.qaStep = qaStep;
	}

	public QaDepData(QaDepDataId id, QaFlow qaFlow, QaStep qaStep, String dataKey, String dataValue, Date createdDt) {
		this.id = id;
		this.qaFlow = qaFlow;
		this.qaStep = qaStep;
		this.dataKey = dataKey;
		this.dataValue = dataValue;
		this.createdDt = createdDt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "depId", column = @Column(name = "DEP_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "flowId", column = @Column(name = "FLOW_ID", nullable = false, precision = 10, scale = 0) ),
			@AttributeOverride(name = "stepId", column = @Column(name = "STEP_ID", nullable = false, precision = 10, scale = 0) ) })
	public QaDepDataId getId() {
		return this.id;
	}

	public void setId(QaDepDataId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLOW_ID", nullable = false, insertable = false, updatable = false)
	public QaFlow getQaFlow() {
		return this.qaFlow;
	}

	public void setQaFlow(QaFlow qaFlow) {
		this.qaFlow = qaFlow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STEP_ID", nullable = false, insertable = false, updatable = false)
	public QaStep getQaStep() {
		return this.qaStep;
	}

	public void setQaStep(QaStep qaStep) {
		this.qaStep = qaStep;
	}

	@Column(name = "DATA_KEY", length = 20)
	public String getDataKey() {
		return this.dataKey;
	}

	public void setDataKey(String dataKey) {
		this.dataKey = dataKey;
	}

	@Column(name = "DATA_VALUE", length = 20)
	public String getDataValue() {
		return this.dataValue;
	}

	public void setDataValue(String dataValue) {
		this.dataValue = dataValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DT", length = 10)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

}
