package org.lightadmin.demo.model;
// Generated Nov 1, 2015 1:04:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QaObject generated by hbm2java
 */
@Entity
@Table(name = "qa_object")
public class QaObject implements java.io.Serializable {

	private Long objId;
	private String objName;
	private String objXpath;
	private String objDesc;
	/*private Set qaTestResults = new HashSet(0);
	private Set qaSteps = new HashSet(0);*/

	public QaObject() {
	}

	public QaObject(Long objId) {
		this.objId = objId;
	}

	public QaObject(Long objId, String objName, String objXpath, String objDesc, Set qaTestResults, Set qaSteps) {
		this.objId = objId;
		this.objName = objName;
		this.objXpath = objXpath;
		this.objDesc = objDesc;
		/*this.qaTestResults = qaTestResults;
		this.qaSteps = qaSteps;*/
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "OBJ_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getObjId() {
		return this.objId;
	}

	public void setObjId(Long objId) {
		this.objId = objId;
	}

	@Column(name = "OBJ_NAME", length = 30)
	public String getObjName() {
		return this.objName;
	}

	public void setObjName(String objName) {
		this.objName = objName;
	}

	@Column(name = "OBJ_XPATH", length = 500)
	public String getObjXpath() {
		return this.objXpath;
	}

	public void setObjXpath(String objXpath) {
		this.objXpath = objXpath;
	}

	@Column(name = "OBJ_DESC", length = 200)
	public String getObjDesc() {
		return this.objDesc;
	}

	public void setObjDesc(String objDesc) {
		this.objDesc = objDesc;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaObject")
	public Set getQaTestResults() {
		return this.qaTestResults;
	}

	public void setQaTestResults(Set qaTestResults) {
		this.qaTestResults = qaTestResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qaObject")
	public Set getQaSteps() {
		return this.qaSteps;
	}

	public void setQaSteps(Set qaSteps) {
		this.qaSteps = qaSteps;
	}
*/
}
