package org.lightadmin.demo.model;
// Generated Nov 5, 2015 6:21:36 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QaTestCaseFlowMap generated by hbm2java
 */
@Entity
@Table(name = "qa_test_case_flow_map")
public class QaTestCaseFlowMap implements java.io.Serializable {

	private Long testCaseFlowMapId;
	private QaFlow qaFlow;
	private QaTestCase qaTestCase;
	private String mappingDesc;
	private Long execSequence;
	private Long depFlow;

	public QaTestCaseFlowMap() {
	}

	public QaTestCaseFlowMap(Long testCaseFlowMapId, QaFlow qaFlow, QaTestCase qaTestCase, Long execSequence) {
		this.testCaseFlowMapId = testCaseFlowMapId;
		this.qaFlow = qaFlow;
		this.qaTestCase = qaTestCase;
		this.execSequence = execSequence;
	}

	public QaTestCaseFlowMap(Long testCaseFlowMapId, QaFlow qaFlow, QaTestCase qaTestCase, String mappingDesc,
			Long execSequence, Long depFlow) {
		this.testCaseFlowMapId = testCaseFlowMapId;
		this.qaFlow = qaFlow;
		this.qaTestCase = qaTestCase;
		this.mappingDesc = mappingDesc;
		this.execSequence = execSequence;
		this.depFlow = depFlow;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "TEST_CASE_FLOW_MAP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getTestCaseFlowMapId() {
		return this.testCaseFlowMapId;
	}

	public void setTestCaseFlowMapId(Long testCaseFlowMapId) {
		this.testCaseFlowMapId = testCaseFlowMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLOW_ID", nullable = false)
	public QaFlow getQaFlow() {
		return this.qaFlow;
	}

	public void setQaFlow(QaFlow qaFlow) {
		this.qaFlow = qaFlow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_CASE_ID", nullable = false)
	public QaTestCase getQaTestCase() {
		return this.qaTestCase;
	}

	public void setQaTestCase(QaTestCase qaTestCase) {
		this.qaTestCase = qaTestCase;
	}

	@Column(name = "MAPPING_DESC", length = 30)
	public String getMappingDesc() {
		return this.mappingDesc;
	}

	public void setMappingDesc(String mappingDesc) {
		this.mappingDesc = mappingDesc;
	}

	@Column(name = "EXEC_SEQUENCE", nullable = false, precision = 10, scale = 0)
	public Long getExecSequence() {
		return this.execSequence;
	}

	public void setExecSequence(Long execSequence) {
		this.execSequence = execSequence;
	}

	@Column(name = "DEP_FLOW", precision = 10, scale = 0)
	public Long getDepFlow() {
		return this.depFlow;
	}

	public void setDepFlow(Long depFlow) {
		this.depFlow = depFlow;
	}

}
