package org.lightadmin.demo.model;
// Generated Nov 1, 2015 4:55:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QaFailure generated by hbm2java
 */
@Entity
@Table(name = "qa_failure")
public class QaFailure implements java.io.Serializable {

	private String threadId;
	private String errorLog;
	private byte[] screenshot;
	private Date createdDt;

	public QaFailure() {
	}

	public QaFailure(String threadId) {
		this.threadId = threadId;
	}

	public QaFailure(String threadId, String errorLog, byte[] screenshot, Date createdDt) {
		this.threadId = threadId;
		this.errorLog = errorLog;
		this.screenshot = screenshot;
		this.createdDt = createdDt;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "THREAD_ID", unique = true, nullable = false, length = 20)
	public String getThreadId() {
		return this.threadId;
	}

	public void setThreadId(String threadId) {
		this.threadId = threadId;
	}

	@Column(name = "ERROR_LOG")
	public String getErrorLog() {
		return this.errorLog;
	}

	public void setErrorLog(String errorLog) {
		this.errorLog = errorLog;
	}

	@Column(name = "SCREENSHOT")
	public byte[] getScreenshot() {
		return this.screenshot;
	}

	public void setScreenshot(byte[] screenshot) {
		this.screenshot = screenshot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DT", length = 10)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

}
