package org.lightadmin.demo.model;
// Generated Nov 5, 2015 4:42:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QaFlowTestMap generated by hbm2java
 */
@Entity
@Table(name = "qa_flow_test_map")
public class QaFlowTestMap implements java.io.Serializable {

	private Long flowTestMapId;
	private QaFlow qaFlow;
	private QaTestResult qaTestResult;
	private Date createDt;
	private String mappingDescription;

	public QaFlowTestMap() {
	}

	public QaFlowTestMap(Long flowTestMapId, QaFlow qaFlow, QaTestResult qaTestResult) {
		this.flowTestMapId = flowTestMapId;
		this.qaFlow = qaFlow;
		this.qaTestResult = qaTestResult;
	}

	public QaFlowTestMap(Long flowTestMapId, QaFlow qaFlow, QaTestResult qaTestResult, Date createDt,
			String mappingDescription) {
		this.flowTestMapId = flowTestMapId;
		this.qaFlow = qaFlow;
		this.qaTestResult = qaTestResult;
		this.createDt = createDt;
		this.mappingDescription = mappingDescription;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "FLOW_TEST_MAP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getFlowTestMapId() {
		return this.flowTestMapId;
	}

	public void setFlowTestMapId(Long flowTestMapId) {
		this.flowTestMapId = flowTestMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLOW_ID", nullable = false)
	public QaFlow getQaFlow() {
		return this.qaFlow;
	}

	public void setQaFlow(QaFlow qaFlow) {
		this.qaFlow = qaFlow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_RESULT_ID", nullable = false)
	public QaTestResult getQaTestResult() {
		return this.qaTestResult;
	}

	public void setQaTestResult(QaTestResult qaTestResult) {
		this.qaTestResult = qaTestResult;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 10)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "MAPPING_DESCRIPTION", length = 200)
	public String getMappingDescription() {
		return this.mappingDescription;
	}

	public void setMappingDescription(String mappingDescription) {
		this.mappingDescription = mappingDescription;
	}

}
