package org.lightadmin.demo.model;
// Generated Nov 5, 2015 3:57:27 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QaFlowStepMap generated by hbm2java
 */
@Entity
@Table(name = "qa_flow_step_map")
public class QaFlowStepMap implements java.io.Serializable {

	private Long flowStepMapId;
	private QaFlow qaFlowByFlowId;
	private QaFlow qaFlowByRefFlowId;
	private QaStep qaStepByRefStepId;
	private QaStep qaStepByStepId;
	private String mappingDesc;
	private Long execSequence;
	private String refKey;

	public QaFlowStepMap() {
	}

	public QaFlowStepMap(Long flowStepMapId, QaFlow qaFlowByFlowId, QaStep qaStepByStepId) {
		this.flowStepMapId = flowStepMapId;
		this.qaFlowByFlowId = qaFlowByFlowId;
		this.qaStepByStepId = qaStepByStepId;
	}

	public QaFlowStepMap(Long flowStepMapId, QaFlow qaFlowByFlowId, QaFlow qaFlowByRefFlowId, QaStep qaStepByRefStepId,
			QaStep qaStepByStepId, String mappingDesc, Long execSequence, String refKey) {
		this.flowStepMapId = flowStepMapId;
		this.qaFlowByFlowId = qaFlowByFlowId;
		this.qaFlowByRefFlowId = qaFlowByRefFlowId;
		this.qaStepByRefStepId = qaStepByRefStepId;
		this.qaStepByStepId = qaStepByStepId;
		this.mappingDesc = mappingDesc;
		this.execSequence = execSequence;
		this.refKey = refKey;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "FLOW_STEP_MAP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getFlowStepMapId() {
		return this.flowStepMapId;
	}

	public void setFlowStepMapId(Long flowStepMapId) {
		this.flowStepMapId = flowStepMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FLOW_ID", nullable = false)
	public QaFlow getQaFlowByFlowId() {
		return this.qaFlowByFlowId;
	}

	public void setQaFlowByFlowId(QaFlow qaFlowByFlowId) {
		this.qaFlowByFlowId = qaFlowByFlowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_FLOW_ID")
	public QaFlow getQaFlowByRefFlowId() {
		return this.qaFlowByRefFlowId;
	}

	public void setQaFlowByRefFlowId(QaFlow qaFlowByRefFlowId) {
		this.qaFlowByRefFlowId = qaFlowByRefFlowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_STEP_ID")
	public QaStep getQaStepByRefStepId() {
		return this.qaStepByRefStepId;
	}

	public void setQaStepByRefStepId(QaStep qaStepByRefStepId) {
		this.qaStepByRefStepId = qaStepByRefStepId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STEP_ID", nullable = false)
	public QaStep getQaStepByStepId() {
		return this.qaStepByStepId;
	}

	public void setQaStepByStepId(QaStep qaStepByStepId) {
		this.qaStepByStepId = qaStepByStepId;
	}

	@Column(name = "MAPPING_DESC", length = 200)
	public String getMappingDesc() {
		return this.mappingDesc;
	}

	public void setMappingDesc(String mappingDesc) {
		this.mappingDesc = mappingDesc;
	}

	@Column(name = "EXEC_SEQUENCE", precision = 10, scale = 0)
	public Long getExecSequence() {
		return this.execSequence;
	}

	public void setExecSequence(Long execSequence) {
		this.execSequence = execSequence;
	}

	@Column(name = "REF_KEY", length = 20)
	public String getRefKey() {
		return this.refKey;
	}

	public void setRefKey(String refKey) {
		this.refKey = refKey;
	}

}
